name: Cypress Tests

on: push

jobs:
    cypress-run:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: E2E tests
              uses: cypress-io/github-action@v5
              with:
                  working-directory: front
                  start: npm run dev, node index.js --prefix back
                  wait-on: 'http://localhost:3000'
                  record: true
              env:
                  CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  NEXT_PUBLIC_IS_DEV: ${{secrets.NEXT_PUBLIC_IS_DEV}}
                  DB_HOST: ${{secrets.DB_HOST}}
                  DB_NAME: ${{secrets.DB_NAME}}
                  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
                  DB_PORT: ${{secrets.DB_PORT}}
                  DB_USER: ${{secrets.DB_USER}}
                  NEXT_PUBLIC_API: ${{secrets.NEXT_PUBLIC_API}}
                  NEXT_PUBLIC_GEOCODING: ${{secrets.NEXT_PUBLIC_GEOCODING}}
                  NEXT_PUBLIC_GMAP: ${{secrets.NEXT_PUBLIC_GMAP}}
                  PORT: ${{secrets.PORT}}
            - name: Unit tests
              uses: cypress-io/github-action@v5
              with:
                  working-directory: front
                  component: true
              env:
                  CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  NEXT_PUBLIC_IS_DEV: ${{secrets.NEXT_PUBLIC_IS_DEV}}
                  DB_HOST: ${{secrets.DB_HOST}}
                  DB_NAME: ${{secrets.DB_NAME}}
                  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
                  DB_PORT: ${{secrets.DB_PORT}}
                  DB_USER: ${{secrets.DB_USER}}
                  NEXT_PUBLIC_API: ${{secrets.NEXT_PUBLIC_API}}
                  NEXT_PUBLIC_GEOCODING: ${{secrets.NEXT_PUBLIC_GEOCODING}}
                  NEXT_PUBLIC_GMAP: ${{secrets.NEXT_PUBLIC_GMAP}}
                  PORT: ${{secrets.PORT}}
